import { addIcons } from 'ionicons';
import {
  add, arrowBack, barcodeOutline, cameraOutline, cart, cartOutline,
  chatbubbleEllipsesOutline, chatbubbles, chevronForward, closeCircleOutline,
  closeOutline, ellipsisHorizontal, fitnessOutline, handLeftOutline, informationCircle,
  location, locationOutline, map, mapOutline, megaphone, mic, micOff,
  navigate, nutritionOutline, personCircleOutline, phonePortrait, phonePortraitOutline, play,
  pricetag, pricetagOutline, pricetagsOutline, reload, remove, restaurant,
  restaurantOutline, scanOutline, search, searchOutline, send, sparkles,
  star, sunnyOutline, trashOutline, videocamOutline, volumeHigh, volumeMute,
  walletOutline, warningOutline
} from 'ionicons/icons';

/**
 * Registro único de íconos de la app (Ionic 8 standalone no los carga solo).
 * Se llama una vez desde main.ts. Al usar un ícono nuevo en un template,
 * agregarlo aquí y no en la página.
 */
export function registerAppIcons(): void {
  addIcons({
    add,
    'arrow-back': arrowBack,
    'barcode-outline': barcodeOutline,
    'camera-outline': cameraOutline,
    cart,
    'cart-outline': cartOutline,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    chatbubbles,
    'chevron-forward': chevronForward,
    'close-circle-outline': closeCircleOutline,
    'close-outline': closeOutline,
    'ellipsis-horizontal': ellipsisHorizontal,
    'fitness-outline': fitnessOutline,
    'hand-left-outline': handLeftOutline,
    'information-circle': informationCircle,
    location,
    'location-outline': locationOutline,
    map,
    'map-outline': mapOutline,
    megaphone,
    mic,
    'mic-off': micOff,
    navigate,
    'nutrition-outline': nutritionOutline,
    'person-circle-outline': personCircleOutline,
    'phone-portrait': phonePortrait,
    'phone-portrait-outline': phonePortraitOutline,
    play,
    pricetag,
    'pricetag-outline': pricetagOutline,
    'pricetags-outline': pricetagsOutline,
    reload,
    remove,
    restaurant,
    'restaurant-outline': restaurantOutline,
    'scan-outline': scanOutline,
    search,
    'search-outline': searchOutline,
    send,
    sparkles,
    star,
    'sunny-outline': sunnyOutline,
    'trash-outline': trashOutline,
    'videocam-outline': videocamOutline,
    'volume-high': volumeHigh,
    'volume-mute': volumeMute,
    'wallet-outline': walletOutline,
    'warning-outline': warningOutline,
  });
}
