import { addIcons } from 'ionicons';
import {
  add, addCircleOutline, addOutline, alertCircle, apps, appsOutline, archiveOutline, arrowBack, arrowForward, barcodeOutline,
  basketOutline, beerOutline, brushOutline, cafeOutline, calculator, calculatorOutline, calendarOutline, cameraOutline, cardOutline,
  cart, cartOutline, chatbubbleEllipsesOutline, chatbubbles, chatbubblesOutline, checkmarkCircle,
  checkmarkDoneCircle, chevronDown, chevronForward, chevronUp, close, closeCircleOutline, closeOutline,
  cube, cubeOutline, ellipsisHorizontal, eyeOutline, fastFoodOutline, fitnessOutline, flame, flameOutline, footstepsOutline,
  giftOutline, globeOutline, gridOutline, handLeftOutline, handRight, handRightOutline, informationCircle,
  layersOutline, leafOutline, listCircle, locateOutline, location, locationOutline, map, mapOutline, medkitOutline, megaphone, megaphoneOutline, mic, micOff,
  navigate, navigateOutline, nutritionOutline, people, peopleOutline, personCircleOutline, phonePortrait,
  phonePortraitOutline, pizzaOutline, play, pricetag, pricetagOutline, pricetags, pricetagsOutline, qrCode, qrCodeOutline,
  reload, remove, removeOutline, restaurant, restaurantOutline, scanOutline, search, searchOutline, send, sparkles,
  sparklesOutline, star, storefrontOutline, sunnyOutline, swapHorizontalOutline, syncOutline, tabletLandscapeOutline, timeOutline,
  trashOutline, videocamOutline, volumeHigh, volumeMute, walletOutline, warning, warningOutline, waterOutline,
  wineOutline, moonOutline
} from 'ionicons/icons';

/**
 * Registro único de íconos de la app (Ionic 8 standalone no los carga solo).
 * Se llama una vez desde main.ts. Al usar un ícono nuevo en un template,
 * agregarlo aquí y no en la página.
 */
export function registerAppIcons(): void {
  addIcons({
    add,
    'add-circle-outline': addCircleOutline,
    'add-outline': addOutline,
    'alert-circle': alertCircle,
    apps,
    'apps-outline': appsOutline,
    'archive-outline': archiveOutline,
    'arrow-back': arrowBack,
    'arrow-forward': arrowForward,
    'barcode-outline': barcodeOutline,
    'basket-outline': basketOutline,
    'beer-outline': beerOutline,
    'brush-outline': brushOutline,
    'cafe-outline': cafeOutline,
    calculator,
    'calculator-outline': calculatorOutline,
    'calendar-outline': calendarOutline,
    'camera-outline': cameraOutline,
    'card-outline': cardOutline,
    cart,
    'cart-outline': cartOutline,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    chatbubbles,
    'chatbubbles-outline': chatbubblesOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-done-circle': checkmarkDoneCircle,
    'chevron-down': chevronDown,
    'chevron-forward': chevronForward,
    'chevron-up': chevronUp,
    close,
    'close-circle-outline': closeCircleOutline,
    'close-outline': closeOutline,
    cube,
    'cube-outline': cubeOutline,
    'ellipsis-horizontal': ellipsisHorizontal,
    'eye-outline': eyeOutline,
    'fast-food-outline': fastFoodOutline,
    'fitness-outline': fitnessOutline,
    flame,
    'flame-outline': flameOutline,
    'footsteps-outline': footstepsOutline,
    'gift-outline': giftOutline,
    'globe-outline': globeOutline,
    'grid-outline': gridOutline,
    'hand-left-outline': handLeftOutline,
    'hand-right': handRight,
    'hand-right-outline': handRightOutline,
    'information-circle': informationCircle,
    'layers-outline': layersOutline,
    'leaf-outline': leafOutline,
    'list-circle': listCircle,
    'locate-outline': locateOutline,
    location,
    'location-outline': locationOutline,
    map,
    'map-outline': mapOutline,
    'medkit-outline': medkitOutline,
    megaphone,
    'megaphone-outline': megaphoneOutline,
    mic,
    'mic-off': micOff,
    'moon-outline': moonOutline,
    navigate,
    'navigate-outline': navigateOutline,
    'nutrition-outline': nutritionOutline,
    people,
    'people-outline': peopleOutline,
    'person-circle-outline': personCircleOutline,
    'phone-portrait': phonePortrait,
    'phone-portrait-outline': phonePortraitOutline,
    'pizza-outline': pizzaOutline,
    play,
    pricetag,
    'pricetag-outline': pricetagOutline,
    'pricetags': pricetags,
    'pricetags-outline': pricetagsOutline,
    'qr-code': qrCode,
    'qr-code-outline': qrCodeOutline,
    reload,
    remove,
    'remove-outline': removeOutline,
    restaurant,
    'restaurant-outline': restaurantOutline,
    'scan-outline': scanOutline,
    search,
    'search-outline': searchOutline,
    send,
    sparkles,
    'sparkles-outline': sparklesOutline,
    star,
    'storefront-outline': storefrontOutline,
    'sunny-outline': sunnyOutline,
    'swap-horizontal-outline': swapHorizontalOutline,
    'sync-outline': syncOutline,
    'tablet-landscape-outline': tabletLandscapeOutline,
    'time-outline': timeOutline,
    'trash-outline': trashOutline,
    'videocam-outline': videocamOutline,
    'volume-high': volumeHigh,
    'volume-mute': volumeMute,
    'wallet-outline': walletOutline,
    warning,
    'warning-outline': warningOutline,
    'water-outline': waterOutline,
    'wine-outline': wineOutline,
  });
}
